x ='Ready to budget';
x = 5;
x = +y;
x = -25;
x = -cos(angle1);
x = +(x*y) ;
x = (x<y) ;
c = 5*(x<y)+12*(x>=y);
y = x in (1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
y = x in (1:10);
y=a**b**c;
y=+(a*b);
z=-(a+b);
c=a*b;
f=g/h;
c=a+b;
f=g-h;
name='J'||'SMITH';
y = x in a;
y = 'Gray'>'Adams';
y = 'C. Jones'<'Charles Jones';
y = (lastname==:'S');
y = (lastname>=:'S');
y = (lastname<=:'S');
y = (16<=age);
y = (16<=age<=65);
y = a<b|c>0;
x = 1 or 2;
x = (not(name=='SMITH'));
x = (name ne 'SMITH');
x = not(a==b & c>d);
x = a ne b | c le d;
x = (cost ne . and cost ne 0);
x = index(address,'Avenue');
x = (A><B);
x = (A<>B);
game=color||name;
d=a||b||c;
newname='Mr. or Ms. ' ||oldname;
name='JOHN   '||'SMITH';
month='sep   ';
year=99;
date=trim(month) || left(put(year,8.));
x = -3><-3 ;
a =  x<y<z ;
